version: '3'
services:
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - "5000:80"
  redis:
    image: redis:3.2
  worker:
    image: dockersamples/examplevotingapp_worker
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - "5001:80"
